#!/bin/sh
# Regenerate the benchmark snapshot table in the docs from a
# results.jsonl produced by ci/bench/competitors.sh. Only the block
# between the snapshot markers is rewritten — prose and footnotes are
# hand-maintained. Exits 0 whether or not anything changed; callers
# diff the file.
set -eu
DOCS="${1:-docs/src/pages/docs/reference/benchmarks.md}"
JSONL="${2:-bench-results/results.jsonl}"

BEGIN='<!-- bench-snapshot:begin (generated by ci/bench/snapshot.sh; edit outside the markers) -->'
END='<!-- bench-snapshot:end -->'

python3 - "$DOCS" "$JSONL" "$BEGIN" "$END" <<'PY'
import json, sys

docs, jsonl, begin, end = sys.argv[1:5]
rows = [json.loads(l) for l in open(jsonl) if l.strip()]
tp = [r for r in rows if r.get("metric") is None]
noise = {r["tool"]: r for r in rows if r.get("metric") == "diff_noise"}
merge = {r["tool"]: r for r in rows if r.get("metric") == "merge3"}
name = {"enprot": "enprot `aes-256-gcm-det`", "sops": "SOPS + age", "gitcrypt": "git-crypt"}

def kb(b):
    return f"{b/1024:.0f} KB" if b < 1024*1024 else f"{b/1024/1024:.1f} MB"

lines = ["| Tool | corpus | enc ms | dec ms | overhead | diff noise | merge |",
         "|------|--------|-------:|-------:|----------:|-----------:|-------|"]
for r in tp:
    tool = r["tool"]
    n = noise.get(tool, {})
    m = merge.get(tool, {})
    raw_n = f"{n.get('changed_lines', '?')}"
    n_txt = raw_n + (" (one segment)" if tool == "enprot" and r["words"] == 8 else "")
    lines.append(
        f"| {name[tool]} | {kb(r['bytes'])} / {r['words']} segs "
        f"| {r['encrypt_ms']} | {r['decrypt_ms']} | {r['overhead_pct']}% "
        f"| {n_txt} | {m.get('different_secrets', '?')} |"
    )

text = open(docs).read()
pre, rest = text.split(begin, 1)
_, post = rest.split(end, 1)
open(docs, "w").write(pre + begin + "\n" + "\n".join(lines) + "\n" + end + post)
PY
