[package]
name = "enprot-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[[bin]]
name = "parse_no_panic"
path = "fuzz_targets/parse_no_panic.rs"
test = false
doc = false

[[bin]]
name = "conflict_well_formed"
path = "fuzz_targets/conflict_well_formed.rs"
test = false
doc = false
