# OUT_DIR-branching toolchain wrappers, baked into the cross images
# (shared by the musl legs and x86_64-pc-windows-gnu).
#
# WHY: rnp-rs's `vendored` feature pulls rnp-src BOTH as a regular
# dependency (the target librnp we link into the binary) AND as a
# build dependency (a HOST librnp that rnp-rs's build.rs generates
# bindings against via bindgen). Both rnp-src build-script runs
# inherit the same environment, so any cross compiler exported for
# the target poisons the host build: mingw objects inside a Linux
# rlib, or zig compiling Botan-for-Linux (issue #368).
#
# HOW: cargo writes build-script output for the cross target under
# target/<triple>/release/build/... and for host artifacts under
# target/release/build/... — the wrappers dispatch on $OUT_DIR,
# which every build script (and its make/cmake children) exports
# and inherits. The deploy matrix then exports ONE set of names
# (tool-cc/tool-cxx/tool-ar/tool-ccbin) and each side transparently
# gets its own toolchain.
#
# Usage: make_wrappers <ctx-dir> <triple> <cc> <cxx> <ar> <ccbin>

set -eu

make_wrappers() {
  ctx=$1 triple=$2 cc=$3 cxx=$4 ar=$5 ccbin=$6
  mkdir -p "$ctx/wrappers"

  _emit() {
    name=$1 target_tool=$2 host_tool=$3
    w="$ctx/wrappers/tool-$name"
    cat > "$w" <<WRAP
#!/bin/sh
# Auto-generated by ci/build-static/pre/wrappers.sh — do not edit.
# OUT_DIR-branching dispatch: target build => $target_tool, host build => $host_tool.
case "\$OUT_DIR" in
  */$triple/*) exec $target_tool "\$@" ;;
  *) exec $host_tool "\$@" ;;
esac
WRAP
    chmod +x "$w"
  }

  _emit cc "$cc" gcc
  _emit cxx "$cxx" g++
  _emit ar "$ar" ar
  _emit ccbin "$ccbin" g++
}
