# OUT_DIR-branching toolchain wrappers, baked into the cross images
# (shared by the musl legs and x86_64-pc-windows-gnu).
#
# WHY: rnp-rs's `vendored` feature pulls rnp-src BOTH as a regular
# dependency (the target librnp we link into the binary) AND as a
# build dependency (a HOST librnp that rnp-rs's build.rs generates
# bindings against via bindgen). Both rnp-src build-script runs
# inherit the same environment, so any cross compiler exported for
# the target poisons the host build: mingw objects inside a Linux
# rlib, or zig compiling Botan-for-Linux (issue #368).
#
# HOW: cargo writes build-script output for the cross target under
# target/<triple>/release/build/... and for host artifacts under
# target/release/build/... — the wrappers dispatch on $OUT_DIR,
# which every build script (and its make/cmake children) exports
# and inherits. The deploy matrix then exports ONE set of names
# (tool-cc/tool-cxx/tool-ar/tool-ccbin) and each side transparently
# gets its own toolchain.
#
# Usage: make_wrappers <ctx-dir> <triple> <cc> <cxx> <ar> <ccbin> [host-cc] [host-cxx]
#
# host-cc/host-cxx default to gcc/g++. The zig legs pass
# clang/clang++: their BOTAN_CONFIGURE_CC_ABI_FLAGS (-mevex512)
# and configure.py's clang-only -W flags must parse on the host
# librnp copy too, so the host side needs a clang-compatible
# driver.

set -eu

make_wrappers() {
  ctx=$1 triple=$2 cc=$3 cxx=$4 ar=$5 ccbin=$6 host_cc=${7:-gcc} host_cxx=${8:-g++}
  mkdir -p "$ctx/wrappers"

  # name is the file to create; the tool-* names are the stable env
  # handles, the bare gcc/g++/cc/c++ names shadow /usr/bin for the
  # hardcoded compiler references rnp-src passes to CMake.
  _emit() {
    name=$1 target_tool=$2 host_tool=$3
    w="$ctx/wrappers/$name"
    cat > "$w" <<WRAP
#!/bin/sh
# Auto-generated by ci/build-static/pre/wrappers.sh — do not edit.
# OUT_DIR-branching dispatch: target build => $target_tool, host build => $host_tool.
case "\$OUT_DIR" in
  */$triple/*) exec $target_tool "\$@" ;;
  *) exec $host_tool "\$@" ;;
esac
WRAP
    chmod +x "$w"
  }

  # Stable env handles (deploy.yml exports TARGET_CC=tool-cc etc).
  _emit tool-cc "$cc" "$host_cc"
  _emit tool-cxx "$cxx" "$host_cxx"
  _emit tool-ar "$ar" ar
  _emit tool-ccbin "$ccbin" "$host_cxx"

  # Shadow the generic compiler names too: rnp-src HARDCODES
  # "gcc"/"g++" for the librnp CMake (-DCMAKE_C(XX)_COMPILER) and
  # bzip2's make — env vars cannot reach those. /usr/local/bin
  # precedes /usr/bin in PATH, so these dispatchers intercept;
  # with OUT_DIR unset (no build-script context) they fall
  # through to the real host compiler, so ad-hoc container use
  # of gcc is unaffected.
  _emit cc "$cc" "$host_cc"
  _emit c++ "$cxx" "$host_cxx"
  _emit gcc "$cc" "$host_cc"
  _emit g++ "$cxx" "$host_cxx"
}
