name: tests

on: [push, pull_request]

jobs:
  build-stable:
    name: Test on stable toolchain
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Build program
        run: |
          # we need a fairly recent botan
          sudo apt update && sudo apt -y install git make g++
          git clone --depth 1 --branch 2.12.1 https://github.com/randombit/botan
          cd botan
          ./configure.py --prefix=/usr --without-documentation
          make -j2
          sudo make install

          cargo build --verbose
        env:
          RUSTFLAGS: -Ctarget-feature=+aes,+ssse3
          RUST_BACKTRACE: full
      - name: Run tests
        run: cargo test --verbose -- --nocapture
        env:
          RUSTFLAGS: -Ctarget-feature=+aes,+ssse3

  check-format:
    name: Check code format
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Validate code format
        run: cargo fmt -- --check $(find src -name '*.rs')
        env:
          RUSTFLAGS: -Ctarget-feature=+aes,+ssse3
